2024-10-02 10:22:36,094 DEBUG    root            Loaded Command Group: ['gcloud', 'compute']
2024-10-02 10:22:36,116 DEBUG    root            Loaded Command Group: ['gcloud', 'compute', 'ssh']
2024-10-02 10:22:36,118 DEBUG    root            Running [gcloud.compute.ssh] with arguments: [--project: "c3labs", --zone: "europe-north1-b", [USER@]INSTANCE: "root@instance-20241001-232901"]
2024-10-02 10:22:36,199 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): compute.googleapis.com:443
2024-10-02 10:22:36,571 DEBUG    urllib3.connectionpool https://compute.googleapis.com:443 "GET /compute/v1/projects/c3labs/zones/europe-north1-b/instances/instance-20241001-232901?alt=json HTTP/1.1" 200 None
2024-10-02 10:22:36,577 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): compute.googleapis.com:443
2024-10-02 10:22:36,979 DEBUG    urllib3.connectionpool https://compute.googleapis.com:443 "GET /compute/v1/projects/c3labs?alt=json HTTP/1.1" 200 None
2024-10-02 10:22:36,987 DEBUG    root            OS Login Enabled: False
2FA Enabled: False
Security Keys Enabled: False
Username: root
Third Party User: False
SSH Security Key Support: None
Environment: None
Security Keys:

Signed SSH Key: False
Require Certificates: False

2024-10-02 10:22:36,989 DEBUG    root            Current SSH keys in project: ['MiguelTavares:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCsGRoFrRnoCeBQAasCV67GsQD4C7vjxRTn0HhOajO8c2HqXJ/Ie+tO9y+XHpwvp2uVX17IsqLrfocJv0aCioUGpZWDh+FoGEm2SHMV0obU4atuWAFBGTtc/JyH++P0p5436E9eebu6RN8xeUQrZ65IEi5Arlh/taioLBdMH+0HJ71qvkjaDqbFE3RSDyDHttYFhC8I+/a9WmaRvQq1SeEjn13fawWB0/QisE7i3aD38FaUz8gTO8FqGVag27ZJRkzzxUsuwwoVcpZ1K5Gu2EaNw6PiTNHvodF7aGVxzfVW6DJDZm68g2W1L4A55J4UjlDhznWVkOZECLgamniK1Ob14WWS3GddTPw3W3OhXt9ntHxDjxr//ZfBB6QDECUk0c4FKaj2ehftY/TS++w/fJCsRtI5MZb+znIYZL8uLEiHmt9Dq17rwYtrkCVR4dVNLfSVlROI/4hWg0JH+O/1mXhs+4CjWOvmnPexi1QPoFkCHM/RNME8hvBHaLmy+dimQS8= MiguelTavares@MiguelTokM1Pro2', 'root:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCsGRoFrRnoCeBQAasCV67GsQD4C7vjxRTn0HhOajO8c2HqXJ/Ie+tO9y+XHpwvp2uVX17IsqLrfocJv0aCioUGpZWDh+FoGEm2SHMV0obU4atuWAFBGTtc/JyH++P0p5436E9eebu6RN8xeUQrZ65IEi5Arlh/taioLBdMH+0HJ71qvkjaDqbFE3RSDyDHttYFhC8I+/a9WmaRvQq1SeEjn13fawWB0/QisE7i3aD38FaUz8gTO8FqGVag27ZJRkzzxUsuwwoVcpZ1K5Gu2EaNw6PiTNHvodF7aGVxzfVW6DJDZm68g2W1L4A55J4UjlDhznWVkOZECLgamniK1Ob14WWS3GddTPw3W3OhXt9ntHxDjxr//ZfBB6QDECUk0c4FKaj2ehftY/TS++w/fJCsRtI5MZb+znIYZL8uLEiHmt9Dq17rwYtrkCVR4dVNLfSVlROI/4hWg0JH+O/1mXhs+4CjWOvmnPexi1QPoFkCHM/RNME8hvBHaLmy+dimQS8= MiguelTavares@MiguelTokM1Pro2']
2024-10-02 10:22:36,989 DEBUG    root            Running command [/usr/bin/ssh -t -i /Users/MiguelTavares/.ssh/google_compute_engine -o CheckHostIP=no -o HashKnownHosts=no -o HostKeyAlias=compute.1849898479687645437 -o IdentitiesOnly=yes -o StrictHostKeyChecking=yes -o UserKnownHostsFile=/Users/MiguelTavares/.ssh/google_compute_known_hosts root@34.88.73.21].
2024-10-02 10:22:36,989 DEBUG    root            Executing command: ['/usr/bin/ssh', '-t', '-i', '/Users/MiguelTavares/.ssh/google_compute_engine', '-o', 'CheckHostIP=no', '-o', 'HashKnownHosts=no', '-o', 'HostKeyAlias=compute.1849898479687645437', '-o', 'IdentitiesOnly=yes', '-o', 'StrictHostKeyChecking=yes', '-o', 'UserKnownHostsFile=/Users/MiguelTavares/.ssh/google_compute_known_hosts', 'root@34.88.73.21']
2024-10-02 10:22:41,861 INFO     ___FILE_ONLY___ 
Recommendation: To check for possible causes of SSH connectivity issues and get
recommendations, rerun the ssh command with the --troubleshoot option.

gcloud compute ssh instance-20241001-232901 --project=c3labs --zone=europe-north1-b --troubleshoot

Or, to investigate an IAP tunneling issue:

gcloud compute ssh instance-20241001-232901 --project=c3labs --zone=europe-north1-b --troubleshoot --tunnel-through-iap


2024-10-02 10:22:41,862 DEBUG    root            (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
Traceback (most recent call last):
  File "/Users/MiguelTavares/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 998, in Execute
    resources = calliope_command.Run(cli=self, args=args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/MiguelTavares/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 842, in Run
    resources = command_instance.Run(args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/MiguelTavares/google-cloud-sdk/lib/surface/compute/ssh.py", line 450, in Run
    raise e
  File "/Users/MiguelTavares/google-cloud-sdk/lib/surface/compute/ssh.py", line 443, in Run
    return_code = cmd.Run(
                  ^^^^^^^^
  File "/Users/MiguelTavares/google-cloud-sdk/lib/googlecloudsdk/command_lib/util/ssh/ssh.py", line 1848, in Run
    raise CommandError(args[0], return_code=status)
googlecloudsdk.command_lib.util.ssh.ssh.CommandError: [/usr/bin/ssh] exited with return code [255].
2024-10-02 10:22:41,866 ERROR    root            (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
